### PR TITLE
Prerequisites for GWT

### PR DESCRIPTION
**Pull request by mbogoevici**

### CODE REVIEW

**Comment by pmuir** [comment]
My only comment is that we should use a conventional name for the section, like "Prerequisites", so we can pull it out on the site, and put it in a popup or a collapsed section

**Comment by mbogoevici** [comment]
I was thinking of "Before we start" as the standard name, but "Prerequisites" is equally fine to me.

**Comment by pmuir** [comment]
Either works. Just needs to be fixed.

**Comment by mbogoevici** [comment]
Not sure what you mean by "fixed". My understanding of all this is that 
we should settle on a single name (it's currently called "Before we 
start")  - or do you mean something else?

**Comment by pmuir** [comment]
The name should be fixed - stay the same :-)

**Pull request merged**
